/**
 * IRL Ambience presets and the Home Assistant automation-blueprint generator.
 *
 * Philosophy: presets are *starting points*, not rigid solutions. Each one
 * produces a valid HA automation blueprint the GM imports and then customizes
 * with HA's native editors. HAmbience never tries to be HA - it just gives a
 * tabletop-flavored on-ramp into HA's own blueprint ecosystem.
 */

export const AMBIENCE_PRESETS = [
  {
    id: "tavern", name: "Tavern", icon: "fa-beer-mug-empty",
    description: "Warm, cozy amber light for inns and taverns.",
    rgb: [255, 147, 41], brightness: 140, transition: 3
  },
  {
    id: "dungeon", name: "Dungeon", icon: "fa-dungeon",
    description: "Cold, dim blue for oppressive underground spaces.",
    rgb: [40, 60, 90], brightness: 50, transition: 4
  },
  {
    id: "forest", name: "Forest", icon: "fa-tree",
    description: "Soft green dappled light for woodland travel.",
    rgb: [60, 160, 70], brightness: 110, transition: 4
  },
  {
    id: "temple", name: "Temple", icon: "fa-place-of-worship",
    description: "Gentle warm gold for sacred and holy places.",
    rgb: [220, 200, 150], brightness: 160, transition: 3
  },
  {
    id: "boss", name: "Boss Encounter", icon: "fa-skull",
    description: "Intense, saturated red for climactic fights.",
    rgb: [200, 30, 30], brightness: 200, transition: 1
  },
  {
    id: "campfire", name: "Campfire", icon: "fa-fire",
    description: "Flickering orange for rests and downtime.",
    rgb: [255, 120, 30], brightness: 120, transition: 2
  },
  {
    id: "storm", name: "Storm", icon: "fa-cloud-bolt",
    description: "Cool blue-grey for tempests and bleak weather.",
    rgb: [120, 140, 200], brightness: 90, transition: 2
  }
];

export function getPreset(id) {
  return AMBIENCE_PRESETS.find(p => p.id === id) ?? null;
}

/**
 * Generate a valid Home Assistant *automation* blueprint for a preset.
 * The blueprint exposes light target / color / brightness / transition as
 * inputs and is triggered by a custom event, so it works natively AND can be
 * force-run via `automation.trigger` from HAmbience's webhook dispatch.
 * @param {object} preset
 * @returns {string} YAML
 */
export function generateBlueprintYaml(preset) {
  const rgb = `[${preset.rgb.join(", ")}]`;
  return `blueprint:
  name: "HAmbience - ${preset.name}"
  description: >
    ${preset.description}
    Generated by HAmbience as a starting point - customize freely with Home
    Assistant's native editors. Trigger it from HAmbience by linking the
    automation this blueprint creates to a Foundry scene.
  domain: automation
  author: HAmbience
  input:
    ambience_lights:
      name: Lights
      description: The lights this ambience controls.
      selector:
        target:
          entity:
            - domain: light
    ambience_color:
      name: Color (RGB)
      description: The mood color for this ambience.
      default: ${rgb}
      selector:
        color_rgb: {}
    ambience_brightness:
      name: Brightness
      description: 1 (dim) to 255 (full).
      default: ${preset.brightness}
      selector:
        number:
          min: 1
          max: 255
          mode: slider
    ambience_transition:
      name: Transition (seconds)
      description: Fade time when the ambience activates.
      default: ${preset.transition}
      selector:
        number:
          min: 0
          max: 30
          mode: slider

mode: restart

trigger:
  - platform: event
    event_type: hambience_activate
    event_data:
      preset: ${preset.id}

condition: []

action:
  - service: light.turn_on
    target: !input ambience_lights
    data:
      rgb_color: !input ambience_color
      brightness: !input ambience_brightness
      transition: !input ambience_transition
`;
}

/* ====================================================================== */
/*  Critical roll blueprints (Nat 20 / Nat 1)                             */
/* ====================================================================== */

export const CRIT_BLUEPRINTS = [
  {
    id: "crit-nat20", name: "Critical Hit (Nat 20)", event: "hambience_crit_nat20",
    description: "A triumphant gold flash when a natural 20 is rolled.",
    rgb: [255, 200, 40]
  },
  {
    id: "crit-nat1", name: "Critical Miss (Nat 1)", event: "hambience_crit_nat1",
    description: "An ominous red flash when a natural 1 is rolled.",
    rgb: [200, 30, 30]
  }
];

export function getCritBlueprint(id) {
  return CRIT_BLUEPRINTS.find(p => p.id === id) ?? null;
}

/**
 * Generate a self-restoring crit-flash automation blueprint. Uses the light
 * "flash" parameter so lights return to their prior state automatically,
 * keeping all revert logic in Home Assistant.
 * @param {object} preset one of CRIT_BLUEPRINTS
 * @returns {string} YAML
 */
export function generateCritBlueprintYaml(preset) {
  const rgb = `[${preset.rgb.join(", ")}]`;
  return `blueprint:
  name: "HAmbience - ${preset.name}"
  description: >
    ${preset.description}
    Generated by HAmbience. The light flash is self-restoring, so your lights
    return to their previous state on their own. An optional sound can play on a
    media player. Link the automation this creates to the matching critical-roll
    preset trigger in HAmbience.
  domain: automation
  author: HAmbience
  input:
    crit_lights:
      name: Lights
      description: The lights to flash on this critical roll.
      selector:
        target:
          entity:
            - domain: light
    crit_color:
      name: Flash Color (RGB)
      default: ${rgb}
      selector:
        color_rgb: {}
    crit_sound:
      name: Sound (optional)
      description: Pick a sound file to play on a critical roll. Leave empty for no sound.
      default: ""
      selector:
        media: {}

mode: restart

trigger:
  - platform: event
    event_type: ${preset.event}

condition: []

variables:
  sound_entity_id: "{{ crit_sound.entity_id if crit_sound is mapping else '' }}"
  sound_content_id: "{{ crit_sound.media_content_id if crit_sound is mapping else '' }}"
  sound_content_type: "{{ crit_sound.media_content_type if crit_sound is mapping else 'music' }}"

action:
  # Slow, self-restoring flash so lights return to their prior state on their own.
  - service: light.turn_on
    target: !input crit_lights
    data:
      rgb_color: !input crit_color
      flash: long
  # Optional sound, only if the media selector was filled in.
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ sound_entity_id != '' and sound_content_id != '' }}"
        sequence:
          - service: media_player.play_media
            target:
              entity_id: "{{ sound_entity_id }}"
            data:
              media_content_id: "{{ sound_content_id }}"
              media_content_type: "{{ sound_content_type }}"
    default: []
`;
}

/* ====================================================================== */
/*  Webhook receiver automation (per-user, unique webhook id)             */
/* ====================================================================== */

/**
 * Build the HA automation that receives HAmbience service calls. A unique
 * webhook id is baked in per user so no two installs share an id.
 * @param {string} webhookId
 * @returns {string} YAML
 */
export function generateReceiverYaml(webhookId) {
  return `alias: HAmbience Webhook Receiver
description: >
  Receives service calls from the HAmbience Foundry VTT module and runs them in
  Home Assistant. Generated with a unique webhook id - keep it private.
mode: queued
max: 10
triggers:
  - trigger: webhook
    webhook_id: ${webhookId}
    allowed_methods:
      - POST
      - PUT
    local_only: false
conditions: []
actions:
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ trigger.json.entity is defined }}"
        sequence:
          - action: "{{ trigger.json.service }}"
            target:
              entity_id: "{{ trigger.json.entity }}"
            data: "{{ trigger.json.data | default({}) }}"
    default:
      - action: "{{ trigger.json.service }}"
        data: "{{ trigger.json.data | default({}) }}"
`;
}
