import {
  MODULE_ID, suggestServices, buildServicePayload
} from "./constants.js";
import { HAClient } from "./ha-client.js";

const { ApplicationV2, HandlebarsApplicationMixin, DialogV2 } = foundry.applications.api;

const F2HA_TAG = "(HAmbience)";

/* ====================================================================== */
/*  Macro Library                                                         */
/* ====================================================================== */

export class F2HAMacroLibrary extends HandlebarsApplicationMixin(ApplicationV2) {
  static DEFAULT_OPTIONS = {
    id: "f2ha-macro-library",
    tag: "div",
    window: { title: "HAmbience - Macro Library", icon: "fas fa-wand-magic-sparkles", contentClasses: ["f2ha", "f2ha-macros"] },
    position: { width: 640, height: "auto" },
    actions: {
      newMacro: F2HAMacroLibrary.#onNew,
      toHotbar: F2HAMacroLibrary.#onToHotbar,
      openMacro: F2HAMacroLibrary.#onOpen,
      deleteMacro: F2HAMacroLibrary.#onDelete
    }
  };

  static PARTS = { body: { template: `modules/${MODULE_ID}/templates/macros.hbs` } };

  async _prepareContext() {
    // Surface macros generated by F2HA (name suffix) plus any that call our API.
    const macros = game.macros.filter(m =>
      m.name?.includes(F2HA_TAG) || (m.command ?? "").includes(`game.modules.get("${MODULE_ID}")`)
    ).map(m => ({ id: m.id, name: m.name }));
    return { macros, hasMacros: macros.length > 0 };
  }

  static async #onNew(event) {
    event.preventDefault();
    if (await F2HAMacroEditor.open()) this.render();
  }

  static async #onOpen(event, target) {
    event.preventDefault();
    const macro = game.macros.get(target.dataset.id);
    macro?.sheet?.render(true);
  }

  static async #onToHotbar(event, target) {
    event.preventDefault();
    const macro = game.macros.get(target.dataset.id);
    if (!macro) return;
    // game.user.hotbar is a {slot: macroId} map of occupied slots on page 1.
    const occupied = game.user.hotbar ?? {};
    let slot = 1;
    while (occupied[slot] && slot <= 50) slot++;
    await game.user.assignHotbarMacro(macro, slot);
    ui.notifications?.info(`HAmbience: assigned "${macro.name}" to hotbar slot ${slot}.`);
  }

  static async #onDelete(event, target) {
    event.preventDefault();
    const macro = game.macros.get(target.dataset.id);
    if (!macro) return;
    const ok = await DialogV2.confirm({
      window: { title: "Delete Macro" },
      content: `<p>Delete the macro <strong>${foundry.utils.escapeHTML(macro.name)}</strong>?</p>`,
      rejectClose: false
    });
    if (!ok) return;
    await macro.delete();
    this.render();
  }
}

/* ====================================================================== */
/*  Macro editor (build a standalone HA-firing macro)                     */
/* ====================================================================== */

export class F2HAMacroEditor extends HandlebarsApplicationMixin(ApplicationV2) {
  constructor(options = {}) {
    super(options);
    this._resolve = options.resolve ?? (() => {});
    this._saved = false;
    const api = game.modules.get(MODULE_ID).api;
    this._hybrid = !!api?.isHybrid;
    this._buildMode = this._hybrid ? "builder" : "raw";
    this._entities = [];
  }

  static DEFAULT_OPTIONS = {
    id: "f2ha-macro-editor",
    tag: "form",
    window: { title: "HAmbience - New Macro", icon: "fas fa-wand-magic-sparkles", contentClasses: ["f2ha", "f2ha-macro-editor"] },
    position: { width: 540, height: "auto" },
    form: { handler: F2HAMacroEditor.#onSubmit, submitOnChange: false, closeOnSubmit: true },
    actions: {
      validatePayload: F2HAMacroEditor.#onValidatePayload,
      refreshEntities: F2HAMacroEditor.#onRefreshEntities,
      setBuildMode: F2HAMacroEditor.#onSetBuildMode
    }
  };

  static PARTS = { form: { template: `modules/${MODULE_ID}/templates/macro-editor.hbs` } };

  static open() {
    return new Promise((resolve) => new F2HAMacroEditor({ resolve }).render(true));
  }

  async _onClose(options) {
    await super._onClose?.(options);
    this._resolve(this._saved === true);
  }

  async _prepareContext() {
    if (this._hybrid && this._buildMode === "builder") {
      this._entities = await HAClient.getEntities();
    }
    return {
      hybrid: this._hybrid,
      buildMode: this._buildMode,
      isBuilder: this._buildMode === "builder",
      entities: this._entities,
      hasEntities: this._entities.length > 0,
      services: [] // populated client-side on entity change
    };
  }

  _onRender() {
    const entitySel = this.element.querySelector('[name="builderEntity"]');
    const serviceSel = this.element.querySelector('[name="builderService"]');
    if (entitySel && serviceSel) {
      const fill = () => {
        const services = suggestServices(entitySel.value);
        serviceSel.innerHTML = services.map(s => `<option value="${s}">${s}</option>`).join("");
      };
      entitySel.addEventListener("change", fill);
      if (entitySel.value) fill();
    }
  }

  static async #onSetBuildMode(event, target) {
    event.preventDefault();
    this._buildMode = target.dataset.mode === "raw" ? "raw" : "builder";
    this.render();
  }

  static async #onRefreshEntities(event) {
    event.preventDefault();
    await HAClient.getEntities({ force: true });
    this.render();
  }

  static #onValidatePayload(event) {
    event.preventDefault();
    const ta = this.element.querySelector('[name="payload"]');
    try {
      ta.value = JSON.stringify(JSON.parse(ta.value || "{}"), null, 2);
      ui.notifications?.info("HAmbience: payload is valid JSON.");
    } catch (err) {
      ui.notifications?.error(`HAmbience: invalid JSON - ${err.message}`);
    }
  }

  #collectPayload() {
    if (this._buildMode === "builder") {
      const entity = this.element.querySelector('[name="builderEntity"]')?.value?.trim();
      const service = this.element.querySelector('[name="builderService"]')?.value?.trim();
      if (!entity || !service) { ui.notifications?.error("HAmbience: pick both an entity and an action."); return null; }
      return buildServicePayload(service, entity);
    }
    const raw = (this.element.querySelector('[name="payload"]')?.value ?? "").trim() || "{}";
    try { JSON.parse(raw); }
    catch (err) { ui.notifications?.error(`HAmbience: invalid payload JSON - ${err.message}`); return null; }
    return raw;
  }

  static async #onSubmit(event, form, formData) {
    const data = foundry.utils.expandObject(formData.object);
    const payload = this.#collectPayload();
    if (payload === null) throw new Error("invalid payload");

    const baseName = (data.name ?? "").trim() || "HA Webhook";
    const command =
`// Auto-generated by Foundry-2-Home Assistant
const api = game.modules.get("${MODULE_ID}")?.api;
if (!api) return ui.notifications.error("HAmbience module not active.");
await api.testDispatch(${JSON.stringify(payload)});`;

    const macro = await Macro.create({
      name: `${baseName} ${F2HA_TAG}`,
      type: "script",
      scope: "global",
      command
    });
    if (macro) ui.notifications?.info(`HAmbience: created macro "${macro.name}".`);
    this._saved = true;
  }
}
